version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node-executor:
    docker:
      - image: cimg/node:16.10

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Use Yarn Berry
          command: yarn set version berry
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false

jobs:
  lint:
    executor: node-executor
    steps:
      - setup
      - run:
          name: Lint code
          command: yarn run lint
  test:
    executor: node-executor
    steps:
      - setup
      - run:
          name: Run tests
          command: yarn run test

workflows:
  general:
    jobs:
      - lint
      - test
