version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node-executor:
    docker:
      - image: cimg/node:16.10

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Use Yarn Berry
          command: yarn set version berry
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false

jobs:
  lint:
    executor: node-executor
    steps:
      - setup
      - run:
          name: Lint code
          command: yarn run lint
  test:
    executor: node-executor
    steps:
      - setup
      - run:
          name: Run tests
          command: yarn run test
  publish:
    executor: node-executor
    steps:
      - setup
      - run:
          name: Publish to NPM
          command: yarn run publish

workflows:
  general:
    jobs:
      - lint
      - test
      - publish:
          requires:
            - lint
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              # Semantic versioning RegEx from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
